### ISSUE TITLE
Cron job not running

### ISSUE THREAD

**Issue by balgerion** [johnpc/subsyncarr#26]
Subsyncer is working without issues on container start, but for some unknown reason, Cron doesn’t trigger new searches

Proof that Subsyncer is working! 😊:
![Image](https://github.com/user-attachments/assets/942d6ae0-627d-46b9-b21e-d600a6c66c9f)

my docker-compose

```
  subsyncarr:
    image: mrorbitman/subsyncarr:latest
    container_name: arr-suite-subsyncarr
    volumes:
      # Any path configured with SCAN_PATHS env var must be mounted
      # If no scan paths are specified, it defaults to scan `/scan_dir` like example below.
      # - ${MEDIA_PATH:-/path/to/your/media}:/scan_dir
      - /mnt/Balgeriada1/Media/movies:/movies
      - /mnt/Balgeriada1/Media/tv-shows:/tv
    restart: unless-stopped
    environment:
      - TZ=Europe/Warsaw
      - CRON_SCHEDULE=30 3 * * *  # Runs every day at midnight by default
      - SCAN_PATHS=/movies,/tv # Remember to mount these as volumes. Must begin with /. Default valus is `/scan_dir`
      #- EXCLUDE_PATHS=/movies/temp,/tv/download # Exclude certain sub-directories from the scan
      - MAX_CONCURRENT_SYNC_TASKS=1
      - INCLUDE_ENGINES=ffsubsync,autosubsync # If not set, all engines are used by default

```

Any idea :) ?
